# Hibernation:
#   Enabled: true
OperationsCenter:
  ServiceType: "ClusterIP"
  Ingress:
    tls:
      Enable: true
      SecretName: "ingress-cert-secret"
    annotations:
      cloud.google.com/load-balancer-type: "Internal"

ingress-nginx:
  Enabled: true
  controller:
    service:
      type: "LoadBalancer"
      targetPorts:
        http: https
        https: https
      annotations:
        cloud.google.com/load-balancer-type: "Internal"
      externalTrafficPolicy: "Local"
